### ISSUE TITLE
[Question] How to charge a Rampage and Sentinel?

### ISSUE THREAD

**Issue by FredGamer** [CurlySparkle/Apex_Sweps#1]

**Comment by Seulyy** [comment]
You have to press E + R if you have a thermite available for the Rampage as for the Sentinel, you'll need at least 50 of armor to activate it

**Comment by TheOnly8Z** [comment]
Press the firemode key (either suitzoom or E+R if set in settings). You can only do it when you have the respective item, or have free charging set to true.
