### ISSUE TITLE
Will Titanfall 2 Weapons be added at some point?

### ISSUE THREAD

**Issue by SnowySnowtime** [CurlySparkle/Apex_Sweps#2]
There's always apex, but never Titanfall 2. Is there a possibility of those being added at some point in the future of the development? If needed, i can provide some of the materials, as i have the heirloom materials on hand for them.

**Comment by kakahost** [comment]
Would be nice, if they can port aimbot smart pistol, but i don't sure that aimbot is possible in ArcCW.

**Comment by Seulyy** [comment]
They planned at some point, yes, but not yet due to some problems with the tool that's used to extract the model n animations in which currently doesn't support TF2 so its hard to work with until they fix that first.
